### ISSUE TITLE
Log in with google suddenly stopped working

### ISSUE THREAD

**Issue by michpau2** [rtCamp/login-with-google#72] opened 2021-05-20 14:24 UTC
I have had this plugin working on multiple sites, across multiple hosting accounts. With different google developer consoles, and suddenly about 2-3 days ago it stopped working. When I click "log in with google" it shows all my google accounts, I choose the correct one, and it just takes me back to the login page to click on "log in with google" again.

**Comment by michpau2** [comment] 2021-05-20 16:18
I have tried deleting the plug and reinstalling it, and I have tried creating a new credential in google developer. Still whenever I try to sign in it just redirects me back to my /wp-login.php page.

**Comment by ankitrox** [comment] 2021-05-20 16:20
@michpau2 Can you add the URL where this issue is happening?

**Comment by michpau2** [comment] 2021-05-20 16:23
It is happening with 5 websites that I am running this plugin on, all the same issue. 3 on one hosting account, and 2 on another separate hosting account. The main site that I am working on and need to get it working again, is https://asd58.us/wp-login.php

**Comment by michpau2** [comment] 2021-05-20 16:53
When I click the "log in with google" button and the list of my accounts shows up, the console has an error that says "VM9:27 This document requires 'TrustedScript' assignment." I'm not sure if this is related or not.

**Comment by michpau2** [comment] 2021-05-20 18:11
I have really enjoyed this plugin, and I would like to not have to move away from it. I have found another plugin that is a little behind this one on some features. I tested it with my current OAuth 2.0 credential that this plugin is using, and the login worked fine with the other plugin, so it cant be an issue with my Google console configs. I have to tinker with the new plugin to get it to work the way I want. So I would really prefer to keep using "login-with-google" if this issue can be resolved. However, I cannot wait long as these are live sites that are needed to be signed into almost daily.

**Comment by ankitrox** [comment] 2021-05-21 10:32
@michpau2 Thanks for details and sorry for inconvenience. 

We have identified a problem in latest version and created a fix for the same. https://github.com/rtCamp/login-with-google/pull/73

A new version for the plugin with this fix will be released soon. If you want to try the fix, you can test it by pulling [this branch](https://github.com/rtCamp/login-with-google/tree/fix/state-decoding)

**Comment by michpau2** [comment] 2021-05-21 14:19
I just downloaded that branch and tested it. Unfortunately, I experienced the same issue.

**Comment by chriselkins** [comment] 2021-05-21 17:49
My sites using the plugin are experiencing the same issue. I also tried using the commit in #73 but I'm still not able to login with Google.

**Comment by ankitrox** [comment] 2021-05-24 08:26
@michpau2 @chriselkins Sorry for the issue. 
We are still investigating the cause for same. However, I have noticed that this issue is not happening in previous version of the plugin **1.0.10**

You can meanwhile, use that version of plugin to avoid this issue. I will keep you posted of further investigation updates.

**Comment by michpau2** [comment] 2021-05-24 14:44
@ankitrox I have tried downloading the 1.0.10 release and downloading it. After uploading it to my WordPress site it I cannot access the settings page. It doesn't appear under the settings page, and on the plugin page it only has the option to deactivate. I am not sure If I did something wrong.

**Comment by pdclark** [comment] 2021-05-25 18:41
@michpau2 @chriselkins @ankitrox An attempted fix has been deployed in version 1.0.13. Does this resolve the issue for you?

**Closed** 2021-06-15 20:24 UTC
