### ISSUE TITLE
QA for 1.3.0 release

### ISSUE THREAD

**Issue by aviral-mittal** [rtCamp/login-with-google#121] opened 2022-09-08 09:16 UTC
## Issue Description

Please conduct a thorough testing of the plugin for upcoming 1.3.0 release. Below are the features, fixes and additions made to the plugin: 

= V 1.3.0 =
* Feature: Gutenberg block for Login button (https://github.com/rtCamp/login-with-google/issues/77)
* Feature: Save user first name and last name on registration (https://github.com/rtCamp/login-with-google/issues/101)
* Add: Added hook after user authentication (https://github.com/rtCamp/login-with-google/issues/89)
* Add: Added hook after user is logged-in (https://github.com/rtCamp/login-with-google/issues/110)
* Fix: set login cookie with shortcode display - https://github.com/rtCamp/rtcamp.com/issues/1415
* Updated npm packages and laravel-mix 
* Fixes https://github.com/rtCamp/login-with-google/issues/112

**Comment by Rink9** [comment] 2022-09-09 06:36
@abhishekfdd @aviral-mittal Performed functional and UI and regression test on Login with Google plugin.

**Functional test cases can be found here:**

 Total scenario tested: 20
 
 https://docs.google.com/spreadsheets/d/1VvThI0j4GluhFk1M-jFwtb8BHdRjl-ciEqdyL-IP8G0/edit?usp=sharing
 
Some feedbacks sharing below

- [ ] 1. On the settings under the `Display Logout ` we can put a text message

`If the user is logged in, keeping this box unchecked will remove the Login with Google button from the page. If the box is checked, the button will show with title changed to ‘Logout’`

<img width="397" alt="image" src="https://user-images.githubusercontent.com/44554636/189284928-6a748f65-581f-4f36-b611-477907309681.png">

- [ ] 2. On logged out mode, after logged in from` Login with Google` button from frontend it's taking to the backend dashboard page.

Expected: After logged in with ` Login with Google` button from frontend we can stay on the frontend page but the page will be logged in.

https://user-images.githubusercontent.com/44554636/189285765-6f74690a-ddbe-4ba0-9ce0-fa1b273e14bd.mp4

------------------

**Note:**

- https://github.com/rtCamp/login-with-google/issues/89
- https://github.com/rtCamp/login-with-google/issues/110
- https://github.com/rtCamp/rtcamp.com/issues/1415

These issues are related to backend cannot verify from my end. Also it has test cases written and verified by @abhishekfdd 

cc: @pooja-muchandikar

**Comment by aviral-mittal** [comment] 2022-09-09 11:55
@Rink9 In the current implementation, point no. 2 is not expected. We have provided hooks in case someone would like to build additional functionalities at authentication or login event.

@abhishek in point no.1, the text can be 

`If the box is unchecked the Login with Google button/block will not be visible to logged-in user. If the box is checked, the button/block will become a ‘Logout’ button`

**Comment by abhishekfdd** [comment] 2022-09-13 07:04
PR for adding helper text is merged now

**Comment by aviral-mittal** [comment] 2022-09-28 12:39
@Souptik2001 @alvitazwar Also need to test the following:

- [ ] Test plugin compatibility with WordPress 5.4.2

**Comment by aviral-mittal** [comment] 2022-09-29 06:51
@alvitazwar Just checking if the findings are available.

**Comment by alvitazwar** [comment] 2022-09-29 07:17
@aviral-mittal can you please elaborate? is there any deadline for this task? I am asking this because I am fully booked on the wp-com task for today.

**Comment by alvitazwar** [comment] 2022-09-29 07:18
> @aviral-mittal can you please elaborate? is there any deadline for this task? I am asking this because I am fully booked on the wp-com task for today.

**Comment by pooja-muchandikar** [comment] 2022-09-29 08:06
@alvitazwar @aviral-mittal 

> Test plugin compatibility with WordPress 5.4.2

Pavan will be working on testing v1.3.0 of Login with Google plugin with WordPress 5.4.2 and the latest stable release along with PHP 7.3/7.4 and quick sanity with PHP 8.1. 

Let us know if any other specific version to be QA'ed. 

Test cases/Checklists for same: https://drive.google.com/drive/folders/1x8Y_GZwZU_0GWNLYeU3R0tK4A1UESu00

cc: @pavanpatil1

**Comment by pavanpatil1** [comment] 2022-09-29 12:46
Tested the login with google v1.3.0 with the WP5.4.2 and the latest WP version. Verified with the PHP7 and 8. Added [status](https://docs.google.com/spreadsheets/d/143XouHaIL0qf7RSbyfqXuZmL2tkFeJvxbfRTM6Db16E/edit#gid=1195729148) below 👇 

1. PHP 7.4 - WP 6.0.2 latest.  - Working fine
2. PHP 7.3.5 - WP 6.0.2 latest - Working fine
4. PHP 7.3.5 - WP5.4.2.  Plugin functionality is working fine. But in the UI of login with google button added from Gutenberg block is showing as a link. It should be visible as a button with the image. 

Actual  result          |  Expected result
:----------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/44057535/193015247-7d4625ea-d9a1-4bbb-b54a-36123f1ae5fe.png)|![image](https://user-images.githubusercontent.com/44057535/193034645-170850da-e438-44b7-8f7c-46a328960151.png)



--

4. Performed the quick sanity with the latest WP and PHP8, No blocker found plugin is working fine. 


---

**General issue observed for the newly added GB block** - 

- [ ] While adding the login with google Gutenberg block, the warning is displayed on the console. Below warning is displayed. 
`Warning: Invalid value for prop `save` on <div> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM`




https://user-images.githubusercontent.com/44057535/192992766-6e457766-257a-4118-8040-947cfd9d2b99.mp4

**Comment by Souptik2001** [comment] 2022-09-30 07:46
Yes I also tested with WP version 5.4.2 and got the same styling problem.

Actually this is because the `style` key in the `register_block_type` function's argument list was most probably introduced in WP version `5.5.0`.

So, either we can change the lower WP version range to `5.5.0` or we can enqueue the `login.css` style separately using `wp_enqueue_style` then we can keep the lower range to `5.4.2` only.

cc: @aviral-mittal @abhishekfdd

**Comment by Souptik2001** [comment] 2022-09-30 08:14
> While adding the login with google Gutenberg block, the warning is displayed on the console.

@pavanpatil1 I tried to produce this console error. But I couldn't see it. If possible can you please provide the edit page link where you are getting this error, so that I can check it?

cc: @aviral-mittal

**Comment by aviral-mittal** [comment] 2022-09-30 09:49
@Souptik2001 Let's update the minimum WP version required in release details to WP5.5 as 5.5. at this time is already 2 years old. 

Cc: @pavanpatil1

**Comment by pavanpatil1** [comment] 2022-10-03 08:56
> While adding the login with google Gutenberg block, the warning is displayed on the console.

Discussed the issue with @Souptik2001. The issue is not reproducible on rt. gw(dev) sites and also on Souptik's local machine. Skipping this for now. So if this issue is reproducible in the future then will try to debug it further. 


cc: @aviral-mittal

**Closed** 2022-10-07 05:57 UTC
Labels: priority/critical, Ready for QA
